### PR TITLE
A quick rewrite of the README, hope this can help

### PR DESCRIPTION
**Pull request by rigobert9**
Your project is what I just needed, thank you so much !
I'm afraid I can't help much, I just rewrote some parts of the README. I will try to send bug reports, keep it up !

### CODE REVIEW

**Comment by rigobert9** [comment]
Just added a correction : the URL in the README was wrong

**Comment by rigobert9** [comment]
Updated the install script so it can be used more widely

**Comment by rigobert9** [comment]
Added a few modifications, like the dependencies, to facilitate installation, that didn't work for me.

**Comment by AlphaTechnolog** [comment]
Oh, thank you a lot! :D

This modifications looks very good! Really thanks :3

**Pull request merged**
